# Generated by Django 4.2 on 2023-04-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 14, 1, 31, 75500, tzinfo=datetime.timezone.utc), null=True, verbose_name='Token Expires Datetime'),
        ),
    ]
