# Generated by Django 4.2 on 2023-04-11 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 9, 3, 58, 832566, tzinfo=datetime.timezone.utc), null=True, verbose_name='Token Expires Datetime'),
        ),
    ]
